#!/bin/bash

get_modules() {

    if [ -d "modules" ]; then
        rm -rf modules
    else
        echo
    fi

    if [ -e "vortex" ]; then
        echo
    else
        curl -LO https://github.com/dibsonthis/Vortex/releases/latest/download/vortex
        chmod 755 vortex
    fi

    mkdir modules

    if [ -e "modules.txt" ]; then
        echo
    else
        echo 'functional
functools
future
io
json
logging
math
os
requests
sdl
string
sys
time' > modules.txt
    fi

    cd modules
    modules_array=()

    while IFS= read -r line || [ -n "$line" ]; do
        trimmed=$(echo -e "$line" | tr -d '[:space:]')
        modules_array+=("$trimmed")
    done < "../modules.txt"

    for module in "${modules_array[@]}"
    do
        curl -LO "https://github.com/dibsonthis/Vortex/releases/latest/download/$module.zip"
        unzip "$module.zip"
        rm "$module.zip"
    done
    cd ..

}

get_modules