#!/bin/bash

get_modules() {

    curl -LO https://github.com/dibsonthis/Vortex/releases/latest/download/mac.zip
    unzip mac.zip

    if [ -d "modules" ]; then
        rm -rf modules
        echo Deleting modules...
    else
        echo
    fi

    if [ -e "vortex" ]; then
        echo Deleting interpreter...
        rm vortex
    else
        echo
    fi

    mv mac/vortex vortex
    chmod 755 vortex

    mkdir modules

    if [ -e "modules.txt" ]; then
        echo
    else
        echo 'functional
functools
future
io
json
logging
math
os
requests
sdl
string
sys
time
random
sqlite' > modules.txt
    fi

    cd modules
    modules_array=()

    while IFS= read -r line || [ -n "$line" ]; do
        trimmed=$(echo -e "$line" | tr -d '[:space:]')
        modules_array+=("$trimmed")
    done < "../modules.txt"

    for module in "${modules_array[@]}"
    do
        mv ../mac/modules/$module $module
    done
    cd ..

    rm -rf mac
    rm -rf mac.zip

}

get_modules